Update latest artifact for HP++
kaist-cp/smr-benchmark pull request #43
Opened 2023-04-20 08:55 UTC by powergee

* Included all materials in HP++ paper artifacts
* Renamed `pebr-benchmark` to `smr-benchmark`
* Rewrite README.md

2023-04-20 09:04 UTC, jeehoonkang requested changes
reviewed

덧:
- rust-toolchain을 보니 nightly를 사용하는데 굳이 그럴 필요가?
- nightly를 꼭 사용해야 한다면 최신으로 업데이트하는 것도 좋을 것 같습니다.

2023-04-20 09:04 UTC, jeehoonkang commented on README.md
> +# General-Purpose SMR Benchmark Suite Written in Rust
Written in Rust는 빼도 될듯

2023-04-20 09:04 UTC, jeehoonkang commented on README.md
> +* Jeehoon Kang and Jaehwang Jung, A Marriage of Pointer- and Epoch-Based Reclamation, PLDI 2020.
순서는 역순으로 (최신 먼저)

2023-04-20 09:04 UTC, jeehoonkang commented on README.md
> +On Ubuntu 18.04 or later,
- 18.04에서도 테스트 되었나요?
- 걍 22.04만 지원해도 괜찮다고 생각합니다.

2023-04-20 09:04 UTC, jeehoonkang commented on README.md
> +This takes several hours and creates raw CSV data under `./results/` and `./results-fine-grained/`.
굳이 폴더가 두개 있는 이유는?

2023-04-20 09:04 UTC, jeehoonkang commented on README.md
> +* data structure: HList, HMList, HHSList, HashMap, NMTree, BonsaiTree, SkipList, EFRBTree
ds, smr scheme에 대해 list up & citation이 필요할지도 모르겠습니다.

2023-04-20 09:04 UTC, jeehoonkang commented on plot.py
>  import warnings
bench/plot python script가 여럿인데 (1) bench.py, plot.py 하나로 합치고 (2) 옵션을 받는건 어떨지? 꼭 그래야하는건 아니니 장단점을 비교해보고 생각해보시면 좋겠습니다.

2023-04-20 09:05 UTC, tomtomjhj requested changes

2023-04-20 09:05 UTC, tomtomjhj commented on README.md
> +# General-Purpose SMR Benchmark Suite Written in Rust
`smr-benchmark`: A microbenchmark suite for concurrent memory reclamation schemes in  Rust

2023-04-20 10:21 UTC, tomtomjhj requested changes

2023-04-20 10:21 UTC, tomtomjhj commented on README.md
>  ## Dependencies
> Linux >= 4.14 for [`MEMBARRIER_CMD_PRIVATE_EXPEDITED` and

HP, HP++ 둘다 요구

2023-04-21 08:38 UTC, powergee commented on plot.py
>  import warnings
bench/plot 스크립트를 통합하는 것에 대해 조금 고민해보았습니다. 그런데 현재 bench.py와 bench-long-running.py 두 스크립트의 성격이 다르고(벤치 대상과 필요한 파라미터가 다름), plot 스크립트들 역시 서로 다른 라이브러리를 사용해서 다른 성격의 데이터를 분석하기 때문에 한 파일로 합치는 것의 장점이 크지 않다고 생각했습니다.

그래서 이 부분은 수정하지 않았지만, 추후 더 좋은 아이디어가 생각나면 다른 방법으로 통합해보겠습니다.

2023-04-21 08:47 UTC, powergee commented
@jeehoonkang @tomtomjhj  bench/plot 스크립트를 합치는 것을 제외한 모든 코멘트를 반영하였습니다.

* nightly toolchain 자체는 필요합니다. 내부적으로 `strict_provenance_atomic_ptr`. `strict_provenance` 에 의존하기 때문입니다.
  * `strict_provenance_atomic_ptr`. `strict_provenance`: `AtomicPtr::fetch_or`를 사용하는 데 필요합니다.
* toolchain을 최신으로 (nightly-2023-04-21) 올렸습니다.

2023-04-24 12:54 UTC, Lee-Janggun requested changes

2023-04-25 04:44 UTC, powergee commented on src/hp/list.rs
> +    ) -> Result<Option<&'hp V>, ()>
명시적으로 `return Err(());`를 하진 않으나 `find`의 return value가 `Err`일 때 propagate하는 부분이 있습니다.

```rust
let found = find(&mut cursor, key)?;
```

2023-04-25 04:59 UTC, powergee commented on src/hp_pp/list.rs
> +        unsafe {
아름답네요... HP 버전에도 반영했습니다. 감사합니다!

2023-04-25 06:02 UTC, powergee commented
@Lee-Janggun 피드백 주셔서 감사합니다. 말씀해주신 것에 추가로 아래 사항을 수정하였습니다.

* HP++의 `List::pop`에서 `next`에 `fetch_or`을 하는 것에도 Acquire Ordering을 적용했습니다.
* HP의 `List::drop`에서 unsafe의 사용 범위를 최소화했습니다.
* `sanitize.sh`를 최신화했습니다.
* CDRC List 구현에서 `fetch_or` 대신 `compare_exchange_mark`를 사용했습니다.

2023-04-25 07:08 UTC, Lee-Janggun commented
@powergee ordering acquire로 바꿔달라고 한거 AcqRel로 바꿔주실수 있나요? 어제 논의했는데 linearizability의 필요조건이 AcqRel입니다.

2023-04-25 07:52 UTC, powergee commented
@Lee-Janggun AcqRel Ordering으로 변경하였습니다.

2023-04-26 15:10 UTC, Lee-Janggun commented
LGTM

2023-04-27 05:51 UTC, merged